export type AppLanguage = 'en' | 'fa';

export interface AccessibilitySettings {
  language: AppLanguage;
  // ADHD & Neurodiversity Friendly Controls
  adhdFocusMode: boolean; // Dims peripheral clutter, highlights single active task
  bionicReading: boolean; // Emphasizes initial letters of words for better focus
  highContrast: boolean; // Maximum contrast mode for visual impairments
  reducedMotion: boolean; // Stops pulsing, floating, confetti and animations
  fontSize: 'normal' | 'large' | 'extra-large'; // Scalable text for visually impaired
  readingRuler: boolean; // Interactive focus guide bar following cursor/touch
  dyslexicFont: boolean; // High legibility letter spacing
  textToSpeechAuto: boolean; // Auto pronounce sentences for cognitive relief
}

export const DEFAULT_ACCESSIBILITY: AccessibilitySettings = {
  language: 'fa', // Default to Persian as requested, with instant toggle
  adhdFocusMode: false,
  bionicReading: false,
  highContrast: false,
  reducedMotion: false,
  fontSize: 'normal',
  readingRuler: false,
  dyslexicFont: false,
  textToSpeechAuto: false,
};

export const TRANSLATIONS = {
  fa: {
    appName: 'انگلیش لینگو',
    citySubtitle: 'پایتخت شهر مجازی توانا',
    map: 'نقشه توانا',
    vocab: 'بازار واژگان',
    grammar: 'تالار گرامر',
    dialogues: 'کافه و مترو',
    speech: 'آزمایشگاه تلفظ',
    quiz: 'میدان آزمون',
    vault: 'خزانه لینگو',
    lingous: 'لینگو طلایی',
    daysStreak: 'روز استمرار',
    level: 'سطح',
    toNextRank: 'تا ارتقای رتبه',
    accessibilityPanel: 'تنظیمات دسترسی‌پذیری و تمرکز (ADHD)',
    adhdMode: 'حالت تمرکز ویژه ADHD',
    adhdModeDesc: 'حذف حواس‌پرتی‌های محیطی، کمرنگ کردن بخش‌های غیرفعال و کادربندی هدفمند',
    bionicReading: 'خوانش شناختی (Bionic Reading)',
    bionicReadingDesc: 'برجسته کردن حروف اول کلمات برای افزایش سرعت درک و جلوگیری از پرش چشم',
    highContrast: 'کنتراست بالا (ویژه کم‌بینایان)',
    reducedMotion: 'کاهش انیمیشن‌ها و لرزش‌ها',
    readingRuler: 'خط‌کش راهنمای مطالعه',
    readingRulerDesc: 'نشانگر خط خوانش برای حفظ تمرکز متن',
    fontSize: 'اندازه قلم و متون',
    fontNormal: 'عادی',
    fontLarge: 'بزرگ',
    fontXLarge: 'بسیار بزرگ',
    soundToggle: 'صدای محیطی و راهنما',
    langToggle: 'تغییر زبان به انگلیسی',
    currentLang: 'فارسی (FA)',
    welcomeBadge: 'خوش آمدید به پایتخت شهر مجازی توانا',
    heroTitle: 'یادگیری عمیق انگلیسی در',
    heroCity: 'شهر توانا',
    heroDesc: 'محیطی تعاملی و متناسب‌سازی شده برای تمامی توان‌یابان و افراد دارای اختلال تمرکز (ADHD). کلمات را در بازار معامله کنید، ساختارهای زبانی را در تالار گرامر بسازید و شمش‌های طلایی لینگو پاداش بگیرید.',
    enterBazaar: 'ورود به بازار واژگان',
    startQuiz: 'شروع آزمون سریع',
    passport: 'گذرنامه شهروندی توانا',
    wordsMastered: 'کلمات تسلط‌یافته',
    todaysDispatch: 'مأموریت‌های روزانه شهر توانا',
    districtsTitle: 'بخش‌های شهر توانا',
    districtsSubtitle: 'برای ورود به هر بخش کلیک کنید',
    openDistrict: 'بخش فعال',
    enterDistrict: 'ورود به بخش',
    flipCard: 'چرخش کارت',
    listenAudio: 'شنیدن تلفظ',
    checkAnswer: 'بررسی پاسخ',
    explanation: 'توضیحات و ریشه‌یابی',
    correct: 'کاملاً درست!',
    incorrect: 'نادرست، دوباره تلاش کنید',
    submit: 'ثبت پاسخ',
    restart: 'شروع مجدد',
    addCustomWord: 'افزودن واژه شخصی',
    monuments: 'بناهای تاریخی توانا',
    restore: 'بازسازی بنا',
    achievements: 'دستاوردهای شهروندی',
    claim: 'دریافت پاداش',
    speed: 'سرعت پخش',
    accent: 'لهجه گفتار',
    close: 'بستن',
    save: 'ذخیره',
  },
  en: {
    appName: 'English-lingou',
    citySubtitle: 'Capital of Virtual Tavana City',
    map: 'Tavana Map',
    vocab: 'Vocab Bazaar',
    grammar: 'Grammar Hall',
    dialogues: 'Café & Metro',
    speech: 'Speech Lab',
    quiz: 'Quiz Arena',
    vault: 'Lingou Vault',
    lingous: 'Golden Lingous',
    daysStreak: 'Days Streak',
    level: 'Level',
    toNextRank: 'to next rank',
    accessibilityPanel: 'Accessibility & ADHD Focus Settings',
    adhdMode: 'ADHD Hyper-Focus Mode',
    adhdModeDesc: 'Dims peripheral distractions and highlights active interactive zones',
    bionicReading: 'Bionic Reading Assistance',
    bionicReadingDesc: 'Boldens initial word letters to guide eye fixations smoothly',
    highContrast: 'High Contrast (Low-Vision)',
    reducedMotion: 'Reduced Motion (No Animations)',
    readingRuler: 'Reading Guide Ruler',
    readingRulerDesc: 'Horizontal eye guide follows screen reading',
    fontSize: 'Text Scaling',
    fontNormal: 'Standard',
    fontLarge: 'Large',
    fontXLarge: 'Extra Large',
    soundToggle: 'Audio & Sound Effects',
    langToggle: 'Switch to Persian',
    currentLang: 'English (EN)',
    welcomeBadge: 'Welcome to the Capital of Virtual Tavana City',
    heroTitle: 'Master English in',
    heroCity: 'Tavana Capital',
    heroDesc: 'An accessible, neurodivergent-friendly learning environment designed for all abilities. Trade in words, construct grammar blueprints, and collect golden Lingous.',
    enterBazaar: 'Enter Vocabulary Bazaar',
    startQuiz: 'Take City Quiz',
    passport: 'Citizen Passport',
    wordsMastered: 'Words Mastered',
    todaysDispatch: "Today's Tavana City Dispatch",
    districtsTitle: 'Tavana Capital Districts',
    districtsSubtitle: 'Select any district to enter and begin practice',
    openDistrict: 'Open District',
    enterDistrict: 'Enter District',
    flipCard: 'Flip Card',
    listenAudio: 'Listen Pronunciation',
    checkAnswer: 'Check Answer',
    explanation: 'Explanation & Insight',
    correct: 'Correct!',
    incorrect: 'Incorrect, try again',
    submit: 'Submit Answer',
    restart: 'Restart',
    addCustomWord: 'Add Word',
    monuments: 'Virtual Tavana Monuments',
    restore: 'Restore Landmark',
    achievements: 'Citizen Achievements',
    claim: 'Claim Reward',
    speed: 'Voice Speed',
    accent: 'Voice Accent',
    close: 'Close',
    save: 'Save',
  }
};
